/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.cassandra.thrift;


/**
 * CQL query compression
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2024-11-08")
public enum Compression implements org.apache.thrift.TEnum {
  GZIP(1),
  NONE(2);

  private final int value;

  private Compression(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Compression findByValue(int value) { 
    switch (value) {
      case 1:
        return GZIP;
      case 2:
        return NONE;
      default:
        return null;
    }
  }
}
