/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.cassandra.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2024-11-08")
public enum IndexOperator implements org.apache.thrift.TEnum {
  EQ(0),
  GTE(1),
  GT(2),
  LTE(3),
  LT(4);

  private final int value;

  private IndexOperator(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static IndexOperator findByValue(int value) { 
    switch (value) {
      case 0:
        return EQ;
      case 1:
        return GTE;
      case 2:
        return GT;
      case 3:
        return LTE;
      case 4:
        return LT;
      default:
        return null;
    }
  }
}
