/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.cassandra.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)", date = "2024-11-08")
public enum IndexType implements org.apache.thrift.TEnum {
  KEYS(0),
  CUSTOM(1),
  COMPOSITES(2);

  private final int value;

  private IndexType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static IndexType findByValue(int value) { 
    switch (value) {
      case 0:
        return KEYS;
      case 1:
        return CUSTOM;
      case 2:
        return COMPOSITES;
      default:
        return null;
    }
  }
}
