/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.cassandra.thrift;
/*
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 */


/**
 * A token returned to the client to indicate the starting column for the next query.
 * If end_of_row is true, then the paging is complete.
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)")
public class PageToken implements org.apache.thrift.TBase<PageToken, PageToken._Fields>, java.io.Serializable, Cloneable, Comparable<PageToken> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PageToken");

  private static final org.apache.thrift.protocol.TField COLUMN_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("column_name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField END_OF_ROW_FIELD_DESC = new org.apache.thrift.protocol.TField("end_of_row", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PageTokenStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PageTokenTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer column_name; // optional
  public boolean end_of_row; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COLUMN_NAME((short)1, "column_name"),
    END_OF_ROW((short)2, "end_of_row");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COLUMN_NAME
          return COLUMN_NAME;
        case 2: // END_OF_ROW
          return END_OF_ROW;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __END_OF_ROW_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.COLUMN_NAME};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COLUMN_NAME, new org.apache.thrift.meta_data.FieldMetaData("column_name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.END_OF_ROW, new org.apache.thrift.meta_data.FieldMetaData("end_of_row", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PageToken.class, metaDataMap);
  }

  public PageToken() {
  }

  public PageToken(
    boolean end_of_row)
  {
    this();
    this.end_of_row = end_of_row;
    setEnd_of_rowIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PageToken(PageToken other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetColumn_name()) {
      this.column_name = org.apache.thrift.TBaseHelper.copyBinary(other.column_name);
    }
    this.end_of_row = other.end_of_row;
  }

  @Override
  public PageToken deepCopy() {
    return new PageToken(this);
  }

  @Override
  public void clear() {
    this.column_name = null;
    setEnd_of_rowIsSet(false);
    this.end_of_row = false;
  }

  public byte[] getColumn_name() {
    setColumn_name(org.apache.thrift.TBaseHelper.rightSize(column_name));
    return column_name == null ? null : column_name.array();
  }

  public java.nio.ByteBuffer bufferForColumn_name() {
    return org.apache.thrift.TBaseHelper.copyBinary(column_name);
  }

  public PageToken setColumn_name(byte[] column_name) {
    this.column_name = column_name == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(column_name.clone());
    return this;
  }

  public PageToken setColumn_name(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer column_name) {
    this.column_name = org.apache.thrift.TBaseHelper.copyBinary(column_name);
    return this;
  }

  public void unsetColumn_name() {
    this.column_name = null;
  }

  /** Returns true if field column_name is set (has been assigned a value) and false otherwise */
  public boolean isSetColumn_name() {
    return this.column_name != null;
  }

  public void setColumn_nameIsSet(boolean value) {
    if (!value) {
      this.column_name = null;
    }
  }

  public boolean isEnd_of_row() {
    return this.end_of_row;
  }

  public PageToken setEnd_of_row(boolean end_of_row) {
    this.end_of_row = end_of_row;
    setEnd_of_rowIsSet(true);
    return this;
  }

  public void unsetEnd_of_row() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __END_OF_ROW_ISSET_ID);
  }

  /** Returns true if field end_of_row is set (has been assigned a value) and false otherwise */
  public boolean isSetEnd_of_row() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __END_OF_ROW_ISSET_ID);
  }

  public void setEnd_of_rowIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __END_OF_ROW_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case COLUMN_NAME:
      if (value == null) {
        unsetColumn_name();
      } else {
        if (value instanceof byte[]) {
          setColumn_name((byte[])value);
        } else {
          setColumn_name((java.nio.ByteBuffer)value);
        }
      }
      break;

    case END_OF_ROW:
      if (value == null) {
        unsetEnd_of_row();
      } else {
        setEnd_of_row((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case COLUMN_NAME:
      return getColumn_name();

    case END_OF_ROW:
      return isEnd_of_row();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case COLUMN_NAME:
      return isSetColumn_name();
    case END_OF_ROW:
      return isSetEnd_of_row();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PageToken)
      return this.equals((PageToken)that);
    return false;
  }

  public boolean equals(PageToken that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_column_name = true && this.isSetColumn_name();
    boolean that_present_column_name = true && that.isSetColumn_name();
    if (this_present_column_name || that_present_column_name) {
      if (!(this_present_column_name && that_present_column_name))
        return false;
      if (!this.column_name.equals(that.column_name))
        return false;
    }

    boolean this_present_end_of_row = true;
    boolean that_present_end_of_row = true;
    if (this_present_end_of_row || that_present_end_of_row) {
      if (!(this_present_end_of_row && that_present_end_of_row))
        return false;
      if (this.end_of_row != that.end_of_row)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetColumn_name()) ? 131071 : 524287);
    if (isSetColumn_name())
      hashCode = hashCode * 8191 + column_name.hashCode();

    hashCode = hashCode * 8191 + ((end_of_row) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(PageToken other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetColumn_name(), other.isSetColumn_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetColumn_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.column_name, other.column_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEnd_of_row(), other.isSetEnd_of_row());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnd_of_row()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.end_of_row, other.end_of_row);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PageToken(");
    boolean first = true;

    if (isSetColumn_name()) {
      sb.append("column_name:");
      if (this.column_name == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.column_name, sb);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("end_of_row:");
    sb.append(this.end_of_row);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'end_of_row' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PageTokenStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PageTokenStandardScheme getScheme() {
      return new PageTokenStandardScheme();
    }
  }

  private static class PageTokenStandardScheme extends org.apache.thrift.scheme.StandardScheme<PageToken> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PageToken struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COLUMN_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.column_name = iprot.readBinary();
              struct.setColumn_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // END_OF_ROW
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.end_of_row = iprot.readBool();
              struct.setEnd_of_rowIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetEnd_of_row()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'end_of_row' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PageToken struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.column_name != null) {
        if (struct.isSetColumn_name()) {
          oprot.writeFieldBegin(COLUMN_NAME_FIELD_DESC);
          oprot.writeBinary(struct.column_name);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(END_OF_ROW_FIELD_DESC);
      oprot.writeBool(struct.end_of_row);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PageTokenTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PageTokenTupleScheme getScheme() {
      return new PageTokenTupleScheme();
    }
  }

  private static class PageTokenTupleScheme extends org.apache.thrift.scheme.TupleScheme<PageToken> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PageToken struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeBool(struct.end_of_row);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetColumn_name()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetColumn_name()) {
        oprot.writeBinary(struct.column_name);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PageToken struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.end_of_row = iprot.readBool();
      struct.setEnd_of_rowIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.column_name = iprot.readBinary();
        struct.setColumn_nameIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

