/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.cassandra.thrift;
/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A column update is a proposal used in cell_cas(). It is expected that the name of the expected and proposed
 * column is the same.
 */
public class ProposedColumnUpdate implements org.apache.thrift.TBase<ProposedColumnUpdate, ProposedColumnUpdate._Fields>, java.io.Serializable, Cloneable, Comparable<ProposedColumnUpdate> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProposedColumnUpdate");

  private static final org.apache.thrift.protocol.TField EXPECTED_COLUMN_FIELD_DESC = new org.apache.thrift.protocol.TField("expected_column", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PROPOSED_COLUMN_FIELD_DESC = new org.apache.thrift.protocol.TField("proposed_column", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ProposedColumnUpdateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ProposedColumnUpdateTupleSchemeFactory());
  }

  public Column expected_column; // optional
  public Column proposed_column; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EXPECTED_COLUMN((short)1, "expected_column"),
    PROPOSED_COLUMN((short)2, "proposed_column");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXPECTED_COLUMN
          return EXPECTED_COLUMN;
        case 2: // PROPOSED_COLUMN
          return PROPOSED_COLUMN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.EXPECTED_COLUMN,_Fields.PROPOSED_COLUMN};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXPECTED_COLUMN, new org.apache.thrift.meta_data.FieldMetaData("expected_column", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Column.class)));
    tmpMap.put(_Fields.PROPOSED_COLUMN, new org.apache.thrift.meta_data.FieldMetaData("proposed_column", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Column.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProposedColumnUpdate.class, metaDataMap);
  }

  public ProposedColumnUpdate() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProposedColumnUpdate(ProposedColumnUpdate other) {
    if (other.isSetExpected_column()) {
      this.expected_column = new Column(other.expected_column);
    }
    if (other.isSetProposed_column()) {
      this.proposed_column = new Column(other.proposed_column);
    }
  }

  public ProposedColumnUpdate deepCopy() {
    return new ProposedColumnUpdate(this);
  }

  @Override
  public void clear() {
    this.expected_column = null;
    this.proposed_column = null;
  }

  public Column getExpected_column() {
    return this.expected_column;
  }

  public ProposedColumnUpdate setExpected_column(Column expected_column) {
    this.expected_column = expected_column;
    return this;
  }

  public void unsetExpected_column() {
    this.expected_column = null;
  }

  /** Returns true if field expected_column is set (has been assigned a value) and false otherwise */
  public boolean isSetExpected_column() {
    return this.expected_column != null;
  }

  public void setExpected_columnIsSet(boolean value) {
    if (!value) {
      this.expected_column = null;
    }
  }

  public Column getProposed_column() {
    return this.proposed_column;
  }

  public ProposedColumnUpdate setProposed_column(Column proposed_column) {
    this.proposed_column = proposed_column;
    return this;
  }

  public void unsetProposed_column() {
    this.proposed_column = null;
  }

  /** Returns true if field proposed_column is set (has been assigned a value) and false otherwise */
  public boolean isSetProposed_column() {
    return this.proposed_column != null;
  }

  public void setProposed_columnIsSet(boolean value) {
    if (!value) {
      this.proposed_column = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EXPECTED_COLUMN:
      if (value == null) {
        unsetExpected_column();
      } else {
        setExpected_column((Column)value);
      }
      break;

    case PROPOSED_COLUMN:
      if (value == null) {
        unsetProposed_column();
      } else {
        setProposed_column((Column)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EXPECTED_COLUMN:
      return getExpected_column();

    case PROPOSED_COLUMN:
      return getProposed_column();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EXPECTED_COLUMN:
      return isSetExpected_column();
    case PROPOSED_COLUMN:
      return isSetProposed_column();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ProposedColumnUpdate)
      return this.equals((ProposedColumnUpdate)that);
    return false;
  }

  public boolean equals(ProposedColumnUpdate that) {
    if (that == null)
      return false;

    boolean this_present_expected_column = true && this.isSetExpected_column();
    boolean that_present_expected_column = true && that.isSetExpected_column();
    if (this_present_expected_column || that_present_expected_column) {
      if (!(this_present_expected_column && that_present_expected_column))
        return false;
      if (!this.expected_column.equals(that.expected_column))
        return false;
    }

    boolean this_present_proposed_column = true && this.isSetProposed_column();
    boolean that_present_proposed_column = true && that.isSetProposed_column();
    if (this_present_proposed_column || that_present_proposed_column) {
      if (!(this_present_proposed_column && that_present_proposed_column))
        return false;
      if (!this.proposed_column.equals(that.proposed_column))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_expected_column = true && (isSetExpected_column());
    builder.append(present_expected_column);
    if (present_expected_column)
      builder.append(expected_column);

    boolean present_proposed_column = true && (isSetProposed_column());
    builder.append(present_proposed_column);
    if (present_proposed_column)
      builder.append(proposed_column);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(ProposedColumnUpdate other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetExpected_column()).compareTo(other.isSetExpected_column());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpected_column()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expected_column, other.expected_column);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProposed_column()).compareTo(other.isSetProposed_column());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProposed_column()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.proposed_column, other.proposed_column);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ProposedColumnUpdate(");
    boolean first = true;

    if (isSetExpected_column()) {
      sb.append("expected_column:");
      if (this.expected_column == null) {
        sb.append("null");
      } else {
        sb.append(this.expected_column);
      }
      first = false;
    }
    if (isSetProposed_column()) {
      if (!first) sb.append(", ");
      sb.append("proposed_column:");
      if (this.proposed_column == null) {
        sb.append("null");
      } else {
        sb.append(this.proposed_column);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (expected_column != null) {
      expected_column.validate();
    }
    if (proposed_column != null) {
      proposed_column.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProposedColumnUpdateStandardSchemeFactory implements SchemeFactory {
    public ProposedColumnUpdateStandardScheme getScheme() {
      return new ProposedColumnUpdateStandardScheme();
    }
  }

  private static class ProposedColumnUpdateStandardScheme extends StandardScheme<ProposedColumnUpdate> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProposedColumnUpdate struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EXPECTED_COLUMN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.expected_column = new Column();
              struct.expected_column.read(iprot);
              struct.setExpected_columnIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROPOSED_COLUMN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.proposed_column = new Column();
              struct.proposed_column.read(iprot);
              struct.setProposed_columnIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProposedColumnUpdate struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.expected_column != null) {
        if (struct.isSetExpected_column()) {
          oprot.writeFieldBegin(EXPECTED_COLUMN_FIELD_DESC);
          struct.expected_column.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.proposed_column != null) {
        if (struct.isSetProposed_column()) {
          oprot.writeFieldBegin(PROPOSED_COLUMN_FIELD_DESC);
          struct.proposed_column.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProposedColumnUpdateTupleSchemeFactory implements SchemeFactory {
    public ProposedColumnUpdateTupleScheme getScheme() {
      return new ProposedColumnUpdateTupleScheme();
    }
  }

  private static class ProposedColumnUpdateTupleScheme extends TupleScheme<ProposedColumnUpdate> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProposedColumnUpdate struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetExpected_column()) {
        optionals.set(0);
      }
      if (struct.isSetProposed_column()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetExpected_column()) {
        struct.expected_column.write(oprot);
      }
      if (struct.isSetProposed_column()) {
        struct.proposed_column.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProposedColumnUpdate struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.expected_column = new Column();
        struct.expected_column.read(iprot);
        struct.setExpected_columnIsSet(true);
      }
      if (incoming.get(1)) {
        struct.proposed_column = new Column();
        struct.proposed_column.read(iprot);
        struct.setProposed_columnIsSet(true);
      }
    }
  }

}

