/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.cassandra.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)")
public class Tracing implements org.apache.thrift.TBase<Tracing, Tracing._Fields>, java.io.Serializable, Cloneable, Comparable<Tracing> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Tracing");

  private static final org.apache.thrift.protocol.TField TRACE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("trace_id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PARENT_SPAN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("parent_span_id", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SPAN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("span_id", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField IS_SAMPLED_FIELD_DESC = new org.apache.thrift.protocol.TField("is_sampled", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField ORIGINATING_SPAN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("originating_span_id", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TracingStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TracingTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String trace_id; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String parent_span_id; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String span_id; // optional
  public boolean is_sampled; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String originating_span_id; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRACE_ID((short)1, "trace_id"),
    PARENT_SPAN_ID((short)2, "parent_span_id"),
    SPAN_ID((short)3, "span_id"),
    IS_SAMPLED((short)4, "is_sampled"),
    ORIGINATING_SPAN_ID((short)5, "originating_span_id");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRACE_ID
          return TRACE_ID;
        case 2: // PARENT_SPAN_ID
          return PARENT_SPAN_ID;
        case 3: // SPAN_ID
          return SPAN_ID;
        case 4: // IS_SAMPLED
          return IS_SAMPLED;
        case 5: // ORIGINATING_SPAN_ID
          return ORIGINATING_SPAN_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_SAMPLED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.TRACE_ID,_Fields.PARENT_SPAN_ID,_Fields.SPAN_ID,_Fields.IS_SAMPLED,_Fields.ORIGINATING_SPAN_ID};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRACE_ID, new org.apache.thrift.meta_data.FieldMetaData("trace_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARENT_SPAN_ID, new org.apache.thrift.meta_data.FieldMetaData("parent_span_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SPAN_ID, new org.apache.thrift.meta_data.FieldMetaData("span_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_SAMPLED, new org.apache.thrift.meta_data.FieldMetaData("is_sampled", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ORIGINATING_SPAN_ID, new org.apache.thrift.meta_data.FieldMetaData("originating_span_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Tracing.class, metaDataMap);
  }

  public Tracing() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Tracing(Tracing other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTrace_id()) {
      this.trace_id = other.trace_id;
    }
    if (other.isSetParent_span_id()) {
      this.parent_span_id = other.parent_span_id;
    }
    if (other.isSetSpan_id()) {
      this.span_id = other.span_id;
    }
    this.is_sampled = other.is_sampled;
    if (other.isSetOriginating_span_id()) {
      this.originating_span_id = other.originating_span_id;
    }
  }

  @Override
  public Tracing deepCopy() {
    return new Tracing(this);
  }

  @Override
  public void clear() {
    this.trace_id = null;
    this.parent_span_id = null;
    this.span_id = null;
    setIs_sampledIsSet(false);
    this.is_sampled = false;
    this.originating_span_id = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTrace_id() {
    return this.trace_id;
  }

  public Tracing setTrace_id(@org.apache.thrift.annotation.Nullable java.lang.String trace_id) {
    this.trace_id = trace_id;
    return this;
  }

  public void unsetTrace_id() {
    this.trace_id = null;
  }

  /** Returns true if field trace_id is set (has been assigned a value) and false otherwise */
  public boolean isSetTrace_id() {
    return this.trace_id != null;
  }

  public void setTrace_idIsSet(boolean value) {
    if (!value) {
      this.trace_id = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getParent_span_id() {
    return this.parent_span_id;
  }

  public Tracing setParent_span_id(@org.apache.thrift.annotation.Nullable java.lang.String parent_span_id) {
    this.parent_span_id = parent_span_id;
    return this;
  }

  public void unsetParent_span_id() {
    this.parent_span_id = null;
  }

  /** Returns true if field parent_span_id is set (has been assigned a value) and false otherwise */
  public boolean isSetParent_span_id() {
    return this.parent_span_id != null;
  }

  public void setParent_span_idIsSet(boolean value) {
    if (!value) {
      this.parent_span_id = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSpan_id() {
    return this.span_id;
  }

  public Tracing setSpan_id(@org.apache.thrift.annotation.Nullable java.lang.String span_id) {
    this.span_id = span_id;
    return this;
  }

  public void unsetSpan_id() {
    this.span_id = null;
  }

  /** Returns true if field span_id is set (has been assigned a value) and false otherwise */
  public boolean isSetSpan_id() {
    return this.span_id != null;
  }

  public void setSpan_idIsSet(boolean value) {
    if (!value) {
      this.span_id = null;
    }
  }

  public boolean isIs_sampled() {
    return this.is_sampled;
  }

  public Tracing setIs_sampled(boolean is_sampled) {
    this.is_sampled = is_sampled;
    setIs_sampledIsSet(true);
    return this;
  }

  public void unsetIs_sampled() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IS_SAMPLED_ISSET_ID);
  }

  /** Returns true if field is_sampled is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_sampled() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IS_SAMPLED_ISSET_ID);
  }

  public void setIs_sampledIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IS_SAMPLED_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOriginating_span_id() {
    return this.originating_span_id;
  }

  public Tracing setOriginating_span_id(@org.apache.thrift.annotation.Nullable java.lang.String originating_span_id) {
    this.originating_span_id = originating_span_id;
    return this;
  }

  public void unsetOriginating_span_id() {
    this.originating_span_id = null;
  }

  /** Returns true if field originating_span_id is set (has been assigned a value) and false otherwise */
  public boolean isSetOriginating_span_id() {
    return this.originating_span_id != null;
  }

  public void setOriginating_span_idIsSet(boolean value) {
    if (!value) {
      this.originating_span_id = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TRACE_ID:
      if (value == null) {
        unsetTrace_id();
      } else {
        setTrace_id((java.lang.String)value);
      }
      break;

    case PARENT_SPAN_ID:
      if (value == null) {
        unsetParent_span_id();
      } else {
        setParent_span_id((java.lang.String)value);
      }
      break;

    case SPAN_ID:
      if (value == null) {
        unsetSpan_id();
      } else {
        setSpan_id((java.lang.String)value);
      }
      break;

    case IS_SAMPLED:
      if (value == null) {
        unsetIs_sampled();
      } else {
        setIs_sampled((java.lang.Boolean)value);
      }
      break;

    case ORIGINATING_SPAN_ID:
      if (value == null) {
        unsetOriginating_span_id();
      } else {
        setOriginating_span_id((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TRACE_ID:
      return getTrace_id();

    case PARENT_SPAN_ID:
      return getParent_span_id();

    case SPAN_ID:
      return getSpan_id();

    case IS_SAMPLED:
      return isIs_sampled();

    case ORIGINATING_SPAN_ID:
      return getOriginating_span_id();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TRACE_ID:
      return isSetTrace_id();
    case PARENT_SPAN_ID:
      return isSetParent_span_id();
    case SPAN_ID:
      return isSetSpan_id();
    case IS_SAMPLED:
      return isSetIs_sampled();
    case ORIGINATING_SPAN_ID:
      return isSetOriginating_span_id();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Tracing)
      return this.equals((Tracing)that);
    return false;
  }

  public boolean equals(Tracing that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_trace_id = true && this.isSetTrace_id();
    boolean that_present_trace_id = true && that.isSetTrace_id();
    if (this_present_trace_id || that_present_trace_id) {
      if (!(this_present_trace_id && that_present_trace_id))
        return false;
      if (!this.trace_id.equals(that.trace_id))
        return false;
    }

    boolean this_present_parent_span_id = true && this.isSetParent_span_id();
    boolean that_present_parent_span_id = true && that.isSetParent_span_id();
    if (this_present_parent_span_id || that_present_parent_span_id) {
      if (!(this_present_parent_span_id && that_present_parent_span_id))
        return false;
      if (!this.parent_span_id.equals(that.parent_span_id))
        return false;
    }

    boolean this_present_span_id = true && this.isSetSpan_id();
    boolean that_present_span_id = true && that.isSetSpan_id();
    if (this_present_span_id || that_present_span_id) {
      if (!(this_present_span_id && that_present_span_id))
        return false;
      if (!this.span_id.equals(that.span_id))
        return false;
    }

    boolean this_present_is_sampled = true && this.isSetIs_sampled();
    boolean that_present_is_sampled = true && that.isSetIs_sampled();
    if (this_present_is_sampled || that_present_is_sampled) {
      if (!(this_present_is_sampled && that_present_is_sampled))
        return false;
      if (this.is_sampled != that.is_sampled)
        return false;
    }

    boolean this_present_originating_span_id = true && this.isSetOriginating_span_id();
    boolean that_present_originating_span_id = true && that.isSetOriginating_span_id();
    if (this_present_originating_span_id || that_present_originating_span_id) {
      if (!(this_present_originating_span_id && that_present_originating_span_id))
        return false;
      if (!this.originating_span_id.equals(that.originating_span_id))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTrace_id()) ? 131071 : 524287);
    if (isSetTrace_id())
      hashCode = hashCode * 8191 + trace_id.hashCode();

    hashCode = hashCode * 8191 + ((isSetParent_span_id()) ? 131071 : 524287);
    if (isSetParent_span_id())
      hashCode = hashCode * 8191 + parent_span_id.hashCode();

    hashCode = hashCode * 8191 + ((isSetSpan_id()) ? 131071 : 524287);
    if (isSetSpan_id())
      hashCode = hashCode * 8191 + span_id.hashCode();

    hashCode = hashCode * 8191 + ((isSetIs_sampled()) ? 131071 : 524287);
    if (isSetIs_sampled())
      hashCode = hashCode * 8191 + ((is_sampled) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetOriginating_span_id()) ? 131071 : 524287);
    if (isSetOriginating_span_id())
      hashCode = hashCode * 8191 + originating_span_id.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Tracing other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetTrace_id(), other.isSetTrace_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTrace_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.trace_id, other.trace_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetParent_span_id(), other.isSetParent_span_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParent_span_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.parent_span_id, other.parent_span_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSpan_id(), other.isSetSpan_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpan_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.span_id, other.span_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIs_sampled(), other.isSetIs_sampled());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_sampled()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_sampled, other.is_sampled);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOriginating_span_id(), other.isSetOriginating_span_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOriginating_span_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.originating_span_id, other.originating_span_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Tracing(");
    boolean first = true;

    if (isSetTrace_id()) {
      sb.append("trace_id:");
      if (this.trace_id == null) {
        sb.append("null");
      } else {
        sb.append(this.trace_id);
      }
      first = false;
    }
    if (isSetParent_span_id()) {
      if (!first) sb.append(", ");
      sb.append("parent_span_id:");
      if (this.parent_span_id == null) {
        sb.append("null");
      } else {
        sb.append(this.parent_span_id);
      }
      first = false;
    }
    if (isSetSpan_id()) {
      if (!first) sb.append(", ");
      sb.append("span_id:");
      if (this.span_id == null) {
        sb.append("null");
      } else {
        sb.append(this.span_id);
      }
      first = false;
    }
    if (isSetIs_sampled()) {
      if (!first) sb.append(", ");
      sb.append("is_sampled:");
      sb.append(this.is_sampled);
      first = false;
    }
    if (isSetOriginating_span_id()) {
      if (!first) sb.append(", ");
      sb.append("originating_span_id:");
      if (this.originating_span_id == null) {
        sb.append("null");
      } else {
        sb.append(this.originating_span_id);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TracingStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TracingStandardScheme getScheme() {
      return new TracingStandardScheme();
    }
  }

  private static class TracingStandardScheme extends org.apache.thrift.scheme.StandardScheme<Tracing> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, Tracing struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRACE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.trace_id = iprot.readString();
              struct.setTrace_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PARENT_SPAN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.parent_span_id = iprot.readString();
              struct.setParent_span_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SPAN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.span_id = iprot.readString();
              struct.setSpan_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IS_SAMPLED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_sampled = iprot.readBool();
              struct.setIs_sampledIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ORIGINATING_SPAN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.originating_span_id = iprot.readString();
              struct.setOriginating_span_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, Tracing struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.trace_id != null) {
        if (struct.isSetTrace_id()) {
          oprot.writeFieldBegin(TRACE_ID_FIELD_DESC);
          oprot.writeString(struct.trace_id);
          oprot.writeFieldEnd();
        }
      }
      if (struct.parent_span_id != null) {
        if (struct.isSetParent_span_id()) {
          oprot.writeFieldBegin(PARENT_SPAN_ID_FIELD_DESC);
          oprot.writeString(struct.parent_span_id);
          oprot.writeFieldEnd();
        }
      }
      if (struct.span_id != null) {
        if (struct.isSetSpan_id()) {
          oprot.writeFieldBegin(SPAN_ID_FIELD_DESC);
          oprot.writeString(struct.span_id);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetIs_sampled()) {
        oprot.writeFieldBegin(IS_SAMPLED_FIELD_DESC);
        oprot.writeBool(struct.is_sampled);
        oprot.writeFieldEnd();
      }
      if (struct.originating_span_id != null) {
        if (struct.isSetOriginating_span_id()) {
          oprot.writeFieldBegin(ORIGINATING_SPAN_ID_FIELD_DESC);
          oprot.writeString(struct.originating_span_id);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TracingTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TracingTupleScheme getScheme() {
      return new TracingTupleScheme();
    }
  }

  private static class TracingTupleScheme extends org.apache.thrift.scheme.TupleScheme<Tracing> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Tracing struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTrace_id()) {
        optionals.set(0);
      }
      if (struct.isSetParent_span_id()) {
        optionals.set(1);
      }
      if (struct.isSetSpan_id()) {
        optionals.set(2);
      }
      if (struct.isSetIs_sampled()) {
        optionals.set(3);
      }
      if (struct.isSetOriginating_span_id()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetTrace_id()) {
        oprot.writeString(struct.trace_id);
      }
      if (struct.isSetParent_span_id()) {
        oprot.writeString(struct.parent_span_id);
      }
      if (struct.isSetSpan_id()) {
        oprot.writeString(struct.span_id);
      }
      if (struct.isSetIs_sampled()) {
        oprot.writeBool(struct.is_sampled);
      }
      if (struct.isSetOriginating_span_id()) {
        oprot.writeString(struct.originating_span_id);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Tracing struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.trace_id = iprot.readString();
        struct.setTrace_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.parent_span_id = iprot.readString();
        struct.setParent_span_idIsSet(true);
      }
      if (incoming.get(2)) {
        struct.span_id = iprot.readString();
        struct.setSpan_idIsSet(true);
      }
      if (incoming.get(3)) {
        struct.is_sampled = iprot.readBool();
        struct.setIs_sampledIsSet(true);
      }
      if (incoming.get(4)) {
        struct.originating_span_id = iprot.readString();
        struct.setOriginating_span_idIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

