/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.cassandra.thrift;
/*
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 */


/**
 * Ids necessary to propagate tracing information across network requests.
 * 
 * Only support the OTEL/W3C propagation information, as we don't support B3-style client/server span sharing. For more
 * information on why this is unncessary, see the following discussions:
 *  - https://github.com/open-telemetry/opentelemetry-specification/issues/1004
 *  - https://github.com/open-telemetry/opentelemetry-python/issues/236
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.17.0)")
public class TraceMetadata implements org.apache.thrift.TBase<TraceMetadata, TraceMetadata._Fields>, java.io.Serializable, Cloneable, Comparable<TraceMetadata> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TraceMetadata");

  private static final org.apache.thrift.protocol.TField TRACE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("trace_id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SPAN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("span_id", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField IS_SAMPLED_FIELD_DESC = new org.apache.thrift.protocol.TField("is_sampled", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TraceMetadataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TraceMetadataTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String trace_id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String span_id; // required
  public boolean is_sampled; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRACE_ID((short)1, "trace_id"),
    SPAN_ID((short)3, "span_id"),
    IS_SAMPLED((short)4, "is_sampled");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRACE_ID
          return TRACE_ID;
        case 3: // SPAN_ID
          return SPAN_ID;
        case 4: // IS_SAMPLED
          return IS_SAMPLED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_SAMPLED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.IS_SAMPLED};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRACE_ID, new org.apache.thrift.meta_data.FieldMetaData("trace_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SPAN_ID, new org.apache.thrift.meta_data.FieldMetaData("span_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_SAMPLED, new org.apache.thrift.meta_data.FieldMetaData("is_sampled", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TraceMetadata.class, metaDataMap);
  }

  public TraceMetadata() {
  }

  public TraceMetadata(
    java.lang.String trace_id,
    java.lang.String span_id)
  {
    this();
    this.trace_id = trace_id;
    this.span_id = span_id;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TraceMetadata(TraceMetadata other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTrace_id()) {
      this.trace_id = other.trace_id;
    }
    if (other.isSetSpan_id()) {
      this.span_id = other.span_id;
    }
    this.is_sampled = other.is_sampled;
  }

  @Override
  public TraceMetadata deepCopy() {
    return new TraceMetadata(this);
  }

  @Override
  public void clear() {
    this.trace_id = null;
    this.span_id = null;
    setIs_sampledIsSet(false);
    this.is_sampled = false;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTrace_id() {
    return this.trace_id;
  }

  public TraceMetadata setTrace_id(@org.apache.thrift.annotation.Nullable java.lang.String trace_id) {
    this.trace_id = trace_id;
    return this;
  }

  public void unsetTrace_id() {
    this.trace_id = null;
  }

  /** Returns true if field trace_id is set (has been assigned a value) and false otherwise */
  public boolean isSetTrace_id() {
    return this.trace_id != null;
  }

  public void setTrace_idIsSet(boolean value) {
    if (!value) {
      this.trace_id = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSpan_id() {
    return this.span_id;
  }

  public TraceMetadata setSpan_id(@org.apache.thrift.annotation.Nullable java.lang.String span_id) {
    this.span_id = span_id;
    return this;
  }

  public void unsetSpan_id() {
    this.span_id = null;
  }

  /** Returns true if field span_id is set (has been assigned a value) and false otherwise */
  public boolean isSetSpan_id() {
    return this.span_id != null;
  }

  public void setSpan_idIsSet(boolean value) {
    if (!value) {
      this.span_id = null;
    }
  }

  public boolean isIs_sampled() {
    return this.is_sampled;
  }

  public TraceMetadata setIs_sampled(boolean is_sampled) {
    this.is_sampled = is_sampled;
    setIs_sampledIsSet(true);
    return this;
  }

  public void unsetIs_sampled() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IS_SAMPLED_ISSET_ID);
  }

  /** Returns true if field is_sampled is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_sampled() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IS_SAMPLED_ISSET_ID);
  }

  public void setIs_sampledIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IS_SAMPLED_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TRACE_ID:
      if (value == null) {
        unsetTrace_id();
      } else {
        setTrace_id((java.lang.String)value);
      }
      break;

    case SPAN_ID:
      if (value == null) {
        unsetSpan_id();
      } else {
        setSpan_id((java.lang.String)value);
      }
      break;

    case IS_SAMPLED:
      if (value == null) {
        unsetIs_sampled();
      } else {
        setIs_sampled((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TRACE_ID:
      return getTrace_id();

    case SPAN_ID:
      return getSpan_id();

    case IS_SAMPLED:
      return isIs_sampled();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TRACE_ID:
      return isSetTrace_id();
    case SPAN_ID:
      return isSetSpan_id();
    case IS_SAMPLED:
      return isSetIs_sampled();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TraceMetadata)
      return this.equals((TraceMetadata)that);
    return false;
  }

  public boolean equals(TraceMetadata that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_trace_id = true && this.isSetTrace_id();
    boolean that_present_trace_id = true && that.isSetTrace_id();
    if (this_present_trace_id || that_present_trace_id) {
      if (!(this_present_trace_id && that_present_trace_id))
        return false;
      if (!this.trace_id.equals(that.trace_id))
        return false;
    }

    boolean this_present_span_id = true && this.isSetSpan_id();
    boolean that_present_span_id = true && that.isSetSpan_id();
    if (this_present_span_id || that_present_span_id) {
      if (!(this_present_span_id && that_present_span_id))
        return false;
      if (!this.span_id.equals(that.span_id))
        return false;
    }

    boolean this_present_is_sampled = true && this.isSetIs_sampled();
    boolean that_present_is_sampled = true && that.isSetIs_sampled();
    if (this_present_is_sampled || that_present_is_sampled) {
      if (!(this_present_is_sampled && that_present_is_sampled))
        return false;
      if (this.is_sampled != that.is_sampled)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTrace_id()) ? 131071 : 524287);
    if (isSetTrace_id())
      hashCode = hashCode * 8191 + trace_id.hashCode();

    hashCode = hashCode * 8191 + ((isSetSpan_id()) ? 131071 : 524287);
    if (isSetSpan_id())
      hashCode = hashCode * 8191 + span_id.hashCode();

    hashCode = hashCode * 8191 + ((isSetIs_sampled()) ? 131071 : 524287);
    if (isSetIs_sampled())
      hashCode = hashCode * 8191 + ((is_sampled) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(TraceMetadata other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetTrace_id(), other.isSetTrace_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTrace_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.trace_id, other.trace_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSpan_id(), other.isSetSpan_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpan_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.span_id, other.span_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIs_sampled(), other.isSetIs_sampled());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_sampled()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_sampled, other.is_sampled);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TraceMetadata(");
    boolean first = true;

    sb.append("trace_id:");
    if (this.trace_id == null) {
      sb.append("null");
    } else {
      sb.append(this.trace_id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("span_id:");
    if (this.span_id == null) {
      sb.append("null");
    } else {
      sb.append(this.span_id);
    }
    first = false;
    if (isSetIs_sampled()) {
      if (!first) sb.append(", ");
      sb.append("is_sampled:");
      sb.append(this.is_sampled);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (trace_id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'trace_id' was not present! Struct: " + toString());
    }
    if (span_id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'span_id' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TraceMetadataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TraceMetadataStandardScheme getScheme() {
      return new TraceMetadataStandardScheme();
    }
  }

  private static class TraceMetadataStandardScheme extends org.apache.thrift.scheme.StandardScheme<TraceMetadata> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TraceMetadata struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRACE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.trace_id = iprot.readString();
              struct.setTrace_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SPAN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.span_id = iprot.readString();
              struct.setSpan_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IS_SAMPLED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_sampled = iprot.readBool();
              struct.setIs_sampledIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TraceMetadata struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.trace_id != null) {
        oprot.writeFieldBegin(TRACE_ID_FIELD_DESC);
        oprot.writeString(struct.trace_id);
        oprot.writeFieldEnd();
      }
      if (struct.span_id != null) {
        oprot.writeFieldBegin(SPAN_ID_FIELD_DESC);
        oprot.writeString(struct.span_id);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIs_sampled()) {
        oprot.writeFieldBegin(IS_SAMPLED_FIELD_DESC);
        oprot.writeBool(struct.is_sampled);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TraceMetadataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TraceMetadataTupleScheme getScheme() {
      return new TraceMetadataTupleScheme();
    }
  }

  private static class TraceMetadataTupleScheme extends org.apache.thrift.scheme.TupleScheme<TraceMetadata> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TraceMetadata struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.trace_id);
      oprot.writeString(struct.span_id);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIs_sampled()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetIs_sampled()) {
        oprot.writeBool(struct.is_sampled);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TraceMetadata struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.trace_id = iprot.readString();
      struct.setTrace_idIsSet(true);
      struct.span_id = iprot.readString();
      struct.setSpan_idIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.is_sampled = iprot.readBool();
        struct.setIs_sampledIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

